#!/bin/sh
#$ -S /bin/bash
#$ -cwd
#$ -N jug_task_array
#$ -t 1-20
#$ -e log_files/$JOB_ID-$TASK_ID.err
#$ -o log_files/$JOB_ID-$TASK_ID.out

# set enviroment
echo "Setting up CMSSW env (for modern ROOT and gcc)"
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc6_amd64_gcc491 
# set area
cd $CMS_USERAREA/releases/CMSSW_7_4_0/src
eval `scramv1 runtime -sh`
cd - &> /dev/null 
echo "CMSSW setup completed"

# call jug execute
jug execute jugfile.py 
